tax_rates_with_currency = {
    "UNITED KINGDOM": {"Tax Rate": 25, "Currency": "£"},
    "IRELAND": {"Tax Rate": 12.5, "Currency": "€"},
    "NETHERLANDS": {"Tax Rate": 25.8, "Currency": "€"},
    "BELGIUM": {"Tax Rate": 25, "Currency": "€"},
    "SOUTH AFRICA": {"Tax Rate": 27, "Currency": "R"},
    "KENYA": {"Tax Rate": 30, "Currency": "KSh"},
    "CANADA": {
        "Federal Tax Rate": 15,
        "Provinces": {
            "ALBERTA": 8,
            "BRITISH COLUMBIA": 12,
            "MANITOBA": 12,
            "NEW BRUNSWICK": 14,
            "NEWFOUNDLAND AND LABRADOR": 15,
            "NORTHWEST TERRITORIES": 11.5,
            "NOVA SCOTIA": 16,
            "NUNAVUT": 12,
            "ONTARIO": 11.5,
            "PRINCE EDWARD ISLAND": 16,
            "QUEBEC": 11.5,
            "SASKATCHEWAN": 12,
            "YUKON": 12
        },
        "Currency": "C$"
    },
    "AUSTRALIA": {
        "Tax Rate": {"Standard": 30, "Small-Medium Business": 25},
        "Currency": "A$"
    },
    "FINLAND": {"Tax Rate": 20, "Currency": "€"},
    "SWEDEN": {"Tax Rate": 20.6, "Currency": "kr"},
    "USA": {
        "Federal Tax Rate": 21,
        "States": {
            "ALABAMA": 6.5,
            "ALASKA": 9.4,
            "ARIZONA": 4.9,
            "ARKANSAS": 5.3,
            "CALIFORNIA": 8.84,
            "COLORADO": 4.4,
            "CONNECTICUT": 7.5,
            "DELAWARE": 8.7,
            "FLORIDA": 5.5,
            "GEORGIA": 5.75,
            "HAWAII": 4.4,
            "IDAHO": 5.8,
            "ILLINOIS": 9.5,
            "INDIANA": 4.9,
            "IOWA": 5.5,
            "KANSAS": 4,
            "KENTUCKY": 5,
            "LOUISIANA": 7.5,
            "MAINE": 8.93,
            "MARYLAND": 8.25,
            "MASSACHUSETTS": 8,
            "MICHIGAN": 6,
            "MINNESOTA": 9.8,
            "MISSISSIPPI": 5,
            "MISSOURI": 4,
            "MONTANA": 6.75,
            "NEBRASKA": 5.84,
            "NEVADA": 0,
            "NEW HAMPSHIRE": 7.6,
            "NEW JERSEY": 9,
            "NEW MEXICO": 5.9,
            "NEW YORK": 7.25,
            "NORTH CAROLINA": 2.5,
            "NORTH DAKOTA": 4.31,
            "OHIO": 0,
            "OKLAHOMA": 4,
            "OREGON": 6.6,
            "PENNSYLVANIA": 4.99,
            "RHODE ISLAND": 7,
            "SOUTH CAROLINA": 5,
            "SOUTH DAKOTA": 0,
            "TENNESSEE": 6.5,
            "TEXAS": 0,
            "UTAH": 4.85,
            "VERMONT": 8.5,
            "VIRGINIA": 6,
            "WASHINGTON": 0,
            "WEST VIRGINIA": 6.5,
            "WISCONSIN": 7.9,
            "WYOMING": 0
        },
        "Currency": "$"
    }
}



